### ISSUE TITLE
Working Directory: null Environment: null - LG G4

### ISSUE THREAD

**Issue by Shahar2k5** [WritingMinds/ffmpeg-android-java#56]
When running ffmpeg on LG G4, i get an error.

all other phones (that i've tested) worked OK.

```
12-06 14:11:03.486 31725-2843/com.dreamdate.app D/CropAndUploadVideoIntentService: ffmpeg.execute onStart
12-06 14:11:03.626 31725-2844/com.dreamdate.app E/FFmpeg: Exception while trying to run: [Ljava.lang.String;@2338732f
                                                          java.io.IOException: Error running exec(). Command: [/data/data/com.myApp.app/files/ffmpeg, -i /data/data/com.myApp.app/app_myApp/ce902ba4ae56d0ced13daf3e5f4a19df.mp4 -strict -2 -c:v libx264 -preset ultrafast -threads 4 -vf crop=1080:1080:420:0 /data/data/com.myApp.app/app_myApp/ce902ba4ae56d0ced13daf3e5f4a19df_new.mp4] Working Directory: null Environment: null
                                                              at java.lang.ProcessManager.exec(ProcessManager.java:211)
                                                              at java.lang.Runtime.exec(Runtime.java:173)
                                                              at java.lang.Runtime.exec(Runtime.java:128)
                                                              at com.github.hiteshsondhi88.libffmpeg.ShellCommand.run(ShellCommand.java:10)
                                                              at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:38)
                                                              at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:10)
                                                              at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                              at java.lang.Thread.run(Thread.java:818)
                                                           Caused by: java.io.IOException: No such file or directory
                                                              at java.lang.ProcessManager.exec(Native Method)
                                                              at java.lang.ProcessManager.exec(ProcessManager.java:209)
                                                              at java.lang.Runtime.exec(Runtime.java:173) 
                                                              at java.lang.Runtime.exec(Runtime.java:128) 
                                                              at com.github.hiteshsondhi88.libffmpeg.ShellCommand.run(ShellCommand.java:10) 
                                                              at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:38) 
                                                              at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:10) 
                                                              at android.os.AsyncTask$2.call(AsyncTask.java:292) 
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                              at java.lang.Thread.run(Thread.java:818) 
12-06 14:11:03.636 31725-31725/com.dreamdate.app D/CropAndUploadVideoIntentService: ffmpeg.execute onFailure ```

**Comment by Shahar2k5** [comment]
The issue was that the library wasnt supporing 64bit devices.
I added support and made a pull request.

**Comment by lucazin** [comment]
shakar2k5 you can help me ?
