### ISSUE TITLE
Error in 2.3.6 device and genimotion emulator

### ISSUE THREAD

**Issue by linslouis** [WritingMinds/ffmpeg-android-java#78]
Error in 2.3.6 device and genimotion emulator

03-10 11:03:18.669 1368-1386/com.github.hiteshsondhi88.sampleffmpeg E/FFmpeg: Exception while trying to run: [Ljava.lang.String;@b649c098
                                                                              java.io.IOException: Error running exec(). Command: [/data/data/com.github.hiteshsondhi88.sampleffmpeg/files/ffmpeg, -f, concat, -i, /mnt/sdcard/FFMPEG/.mergelist.txt, -c, copy, /mnt/sdcard/FFMPEG/Merged/Merged2016-03-10-11-03-17.mp3] Working Directory: null Environment: null
                                                                                  at java.lang.ProcessManager.exec(ProcessManager.java:224)
                                                                                  at java.lang.Runtime.exec(Runtime.java:189)
                                                                                  at java.lang.Runtime.exec(Runtime.java:136)
                                                                                  at com.github.hiteshsondhi88.libffmpeg.ShellCommand.run(ShellCommand.java:10)
                                                                                  at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:38)
                                                                                  at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:10)
                                                                                  at android.os.AsyncTask$2.call(AsyncTask.java:185)
                                                                                  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
                                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:138)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
                                                                                  at java.lang.Thread.run(Thread.java:1019)
                                                                               Caused by: java.io.IOException: Permission denied
                                                                                  at java.lang.ProcessManager.exec(Native Method)
                                                                                  at java.lang.ProcessManager.exec(ProcessManager.java:222)
                                                                                  at java.lang.Runtime.exec(Runtime.java:189) 
                                                                                  at java.lang.Runtime.exec(Runtime.java:136) 
                                                                                  at com.github.hiteshsondhi88.libffmpeg.ShellCommand.run(ShellCommand.java:10) 
                                                                                  at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:38) 
                                                                                  at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:10) 
                                                                                  at android.os.AsyncTask$2.call(AsyncTask.java:185) 
                                                                                  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306) 
                                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:138) 
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088) 
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581) 
                                                                                  at java.lang.Thread.run(Thread.java:1019)

**Comment by hiteshsondhi88** [comment]
This library only supports 4.1+ devices. You need to compile binaries on your own to support 2.3.6.
